In [10]:
# Great now that I have done that, play around with this shape file,
# First things first, gotta make the relevant imports
import geopandas as gpd
from pathlib import Path

In [2]:
#AusBS_Zones = ABS_Zones, can't name it that cause python sees ABS as a math function
data_path = '../data/geospatial_data/SA2_2021_AUST_GDA2020/data.shp'
AusBS_Zones = gpd.read_file(data_path)

In [3]:
# An overveiw of my whole dataframe, seems like:

# SA2_CODE21 provides a unique ID for a localised area
# SA2_NAME21 provides a nume for this localised are

#####################################################################
# CHG_FLAG21 - is a code to describe my best guess, if the data has
# the data has changed or not 3 codes are relevant to VIC, 0, 1, 3
# CHG_LBL21 - 0 = no change, 1 = new, 3 = name change
######################################################################

# SA3_CODE21 - provides a unique ID for a larger area than SA2
# SA3_NAME21 - is the name for SA3_CODE

# SA4_CODE21 - unique code for even larger areas
# SA4_NAME21 - is the name for that

##################################################################
# GCC_CODE21 - unique ID for either rest of vic, greater vic, 
# migratory off shore vic, or no usual location vic
# GCC_NAME21 - is the name as listed above in GCC_CODE21
##################################################################



# STE_CODE21 - what state it is but code for that
# STE_NAME21 - name for relevant code

# AUS_CODE21 - all 'AUS' expect final entry
# AUS_NAME21 - all Australia expect last one, Outside Australia

# AREASQKM21 - Square kilometeres of SA2 zone
# LOCI_URI21 - is a link, yet to go there
# geometry - is geometry yay!!!
AusBS_Zones.head(1)

,SA2_CODE21,SA2_NAME21,CHG_FLAG21,CHG_LBL21,SA3_CODE21,SA3_NAME21,SA4_CODE21,SA4_NAME21,GCC_CODE21,GCC_NAME21,STE_CODE21,STE_NAME21,AUS_CODE21,AUS_NAME21,AREASQKM21,LOCI_URI21,geometry
0,101021007,Braidwood,0,No change,10102,Queanbeyan,101,Capital Region,1RNSW,Rest of NSW,1,New South Wales,AUS,Australia,3418.3525,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"POLYGON ((149.58424 -35.44426, 149.58444 -35.4..."

In [4]:
# Now to filter areas only in victoria,

Vic_Filt = (AusBS_Zones["STE_NAME21"] == "Victoria")

AusBS_Vic_Zones = AusBS_Zones[Vic_Filt]

In [5]:
AusBS_Vic_Zones.head(1)

,SA2_CODE21,SA2_NAME21,CHG_FLAG21,CHG_LBL21,SA3_CODE21,SA3_NAME21,SA4_CODE21,SA4_NAME21,GCC_CODE21,GCC_NAME21,STE_CODE21,STE_NAME21,AUS_CODE21,AUS_NAME21,AREASQKM21,LOCI_URI21,geometry
644,201011001,Alfredton,0,No change,20101,Ballarat,201,Ballarat,2RVIC,Rest of Vic.,2,Victoria,AUS,Australia,52.7109,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"POLYGON ((143.78282 -37.56666, 143.75558 -37.5..."

In [6]:
# Cool may drop the no usual address & Migratory - offshore shipping
AusBS_Vic_Zones["CHG_LBL21"].value_counts(dropna=False)

CHG_LBL21
No change      380
New            114
Name change     30
Name: count, dtype: int64

In [7]:
AusBS_Vic_Zones["GCC_NAME21"].unique()

array(['Rest of Vic.', 'Greater Melbourne',
       'Migratory - Offshore - Shipping (Vic.)',
       'No usual address (Vic.)'], dtype=object)

In [8]:
##########################################################
# Now to drop some of these rows & coloums  
# that i dont need in this dataframe to save storage
##########################################################

AusBS_Vic_Zones = AusBS_Vic_Zones.drop(columns=[
    "CHG_FLAG21",
    "CHG_LBL21",
    "STE_CODE21",
    "STE_NAME21",
    "AUS_CODE21",
    "AUS_NAME21"
    ]
)

AusBS_Vic_Zones = AusBS_Vic_Zones.dropna(
    subset=["AREASQKM21"]
)

In [11]:
# Make sure the file path exists cause of .gitignore
Vic_Zones_Data_Path = Path("../data/area_zones_data")
Vic_Zones_Data_Path.mkdir(parents=True, exist_ok=True)

AusBS_Vic_Zones.to_file(Vic_Zones_Data_Path/"Vic_Area_Zones.shp")