In [15]:
# Great now that I have done that, play around with this shape file,
# First things first, gotta make the relevant imports

import geopandas as gpd

In [16]:
#AusBS_Zones = ABS_Zones, can't name it that cause python sees ABS as a math function
data_path = '../data/geospatial_data/SA2_2021_AUST_GDA2020/data.shp'
AusBS_Zones = gpd.read_file(data_path)

In [17]:
# An overveiw of my whole dataframe, seems like:

# SA2_CODE21 provides a unique ID for a localised area
# SA2_NAME21 provides a nume for this localised are

#####################################################################
# CHG_FLAG21 - is a code to describe my best guess, if the data has
# the data has changed or not 3 codes are relevant to VIC, 0, 1, 3
# CHG_LBL21 - 0 = no change, 1 = new, 3 = name change
######################################################################

# SA3_CODE21 - provides a unique ID for a larger area than SA2
# SA3_NAME21 - is the name for SA3_CODE

# SA4_CODE21 - unique code for even larger areas
# SA4_NAME21 - is the name for that

##################################################################
# GCC_CODE21 - unique ID for either rest of vic, greater vic, 
# migratory off shore vic, or no usual location vic
# GCC_NAME21 - is the name as listed above in GCC_CODE21
##################################################################



# STE_CODE21 - what state it is but code for that
# STE_NAME21 - name for relevant code

# AUS_CODE21 - all 'AUS' expect final entry
# AUS_NAME21 - all Australia expect last one, Outside Australia

# AREASQKM21 - Square kilometeres of SA2 zone
# LOCI_URI21 - is a link, yet to go there
# geometry - is geometry yay!!!





AusBS_Zones

,SA2_CODE21,SA2_NAME21,CHG_FLAG21,CHG_LBL21,SA3_CODE21,SA3_NAME21,SA4_CODE21,SA4_NAME21,GCC_CODE21,GCC_NAME21,STE_CODE21,STE_NAME21,AUS_CODE21,AUS_NAME21,AREASQKM21,LOCI_URI21,geometry
0,101021007,Braidwood,0,No change,10102,Queanbeyan,101,Capital Region,1RNSW,Rest of NSW,1,New South Wales,AUS,Australia,3418.3525,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"POLYGON ((149.58424 -35.44426, 149.58444 -35.4..."
1,101021008,Karabar,0,No change,10102,Queanbeyan,101,Capital Region,1RNSW,Rest of NSW,1,New South Wales,AUS,Australia,6.9825,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"POLYGON ((149.21899 -35.36738, 149.218 -35.366..."
2,101021009,Queanbeyan,0,No change,10102,Queanbeyan,101,Capital Region,1RNSW,Rest of NSW,1,New South Wales,AUS,Australia,4.7620,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"POLYGON ((149.21326 -35.34325, 149.21619 -35.3..."
3,101021010,Queanbeyan - East,0,No change,10102,Queanbeyan,101,Capital Region,1RNSW,Rest of NSW,1,New South Wales,AUS,Australia,13.0032,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"POLYGON ((149.24034 -35.34781, 149.24024 -35.3..."
4,101021012,Queanbeyan West - Jerrabomberra,0,No change,10102,Queanbeyan,101,Capital Region,1RNSW,Rest of NSW,1,New South Wales,AUS,Australia,13.6748,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"POLYGON ((149.19572 -35.36126, 149.1997 -35.35..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2468,901031003,Jervis Bay,0,No change,90103,Jervis Bay,901,Other Territories,9OTER,Other Territories,9,Other Territories,AUS,Australia,67.2296,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"MULTIPOLYGON (((150.69567 -35.18295, 150.69556..."
2469,901041004,Norfolk Island,0,No change,90104,Norfolk Island,901,Other Territories,9OTER,Other Territories,9,Other Territories,AUS,Australia,38.6510,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"MULTIPOLYGON (((167.96325 -29.07212, 167.96326..."
2470,997979799,Migratory - Offshore - Shipping (OT),0,No change,99797,Migratory - Offshore - Shipping (OT),997,Migratory - Offshore - Shipping (OT),99799,Migratory - Offshore - Shipping (OT),9,Other Territories,AUS,Australia,NaN,http://linked.data.gov.au/dataset/asgsed3/SA2/...,None
2471,999999499,No usual address (OT),0,No change,99999,No usual address (OT),999,No usual address (OT),99499,No usual address (OT),9,Other Territories,AUS,Australia,NaN,http://linked.data.gov.au/dataset/asgsed3/SA2/...,None
2472,ZZZZZZZZZ,Outside Australia,1,New,ZZZZZ,Outside Australia,ZZZ,Outside Australia,ZZZZZ,Outside Australia,Z,Outside Australia,ZZZ,Outside Australia,NaN,http://linked.data.gov.au/dataset/asgsed3/SA2/...,None

In [18]:
# Now to filter areas only in victoria,

Vic_Filt = (AusBS_Zones["STE_NAME21"] == "Victoria")

AusBS_Vic_Zones = AusBS_Zones[Vic_Filt]

In [19]:
AusBS_Vic_Zones

,SA2_CODE21,SA2_NAME21,CHG_FLAG21,CHG_LBL21,SA3_CODE21,SA3_NAME21,SA4_CODE21,SA4_NAME21,GCC_CODE21,GCC_NAME21,STE_CODE21,STE_NAME21,AUS_CODE21,AUS_NAME21,AREASQKM21,LOCI_URI21,geometry
644,201011001,Alfredton,0,No change,20101,Ballarat,201,Ballarat,2RVIC,Rest of Vic.,2,Victoria,AUS,Australia,52.7109,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"POLYGON ((143.78282 -37.56666, 143.75558 -37.5..."
645,201011002,Ballarat,0,No change,20101,Ballarat,201,Ballarat,2RVIC,Rest of Vic.,2,Victoria,AUS,Australia,12.3787,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"POLYGON ((143.81896 -37.55582, 143.81644 -37.5..."
646,201011005,Buninyong,0,No change,20101,Ballarat,201,Ballarat,2RVIC,Rest of Vic.,2,Victoria,AUS,Australia,51.5855,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"POLYGON ((143.84171 -37.61596, 143.84176 -37.6..."
647,201011006,Delacombe,0,No change,20101,Ballarat,201,Ballarat,2RVIC,Rest of Vic.,2,Victoria,AUS,Australia,34.1607,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"POLYGON ((143.7505 -37.59119, 143.75044 -37.59..."
648,201011007,Smythes Creek,0,No change,20101,Ballarat,201,Ballarat,2RVIC,Rest of Vic.,2,Victoria,AUS,Australia,104.7274,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"POLYGON ((143.73296 -37.62333, 143.73263 -37.6..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1163,217041478,Moyne - West,0,No change,21704,Warrnambool,217,Warrnambool and South West,2RVIC,Rest of Vic.,2,Victoria,AUS,Australia,2037.7626,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"MULTIPOLYGON (((142.0087 -38.41715, 142.00876 ..."
1164,217041479,Warrnambool - North,0,No change,21704,Warrnambool,217,Warrnambool and South West,2RVIC,Rest of Vic.,2,Victoria,AUS,Australia,62.4199,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"POLYGON ((142.43668 -38.35544, 142.43658 -38.3..."
1165,217041480,Warrnambool - South,0,No change,21704,Warrnambool,217,Warrnambool and South West,2RVIC,Rest of Vic.,2,Victoria,AUS,Australia,120.1957,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"POLYGON ((142.45281 -38.39126, 142.4523 -38.39..."
1166,297979799,Migratory - Offshore - Shipping (Vic.),0,No change,29797,Migratory - Offshore - Shipping (Vic.),297,Migratory - Offshore - Shipping (Vic.),29799,Migratory - Offshore - Shipping (Vic.),2,Victoria,AUS,Australia,NaN,http://linked.data.gov.au/dataset/asgsed3/SA2/...,None
1167,299999499,No usual address (Vic.),0,No change,29999,No usual address (Vic.),299,No usual address (Vic.),29499,No usual address (Vic.),2,Victoria,AUS,Australia,NaN,http://linked.data.gov.au/dataset/asgsed3/SA2/...,None

In [20]:
# Cool may drop the no usual address & Migratory - offshore shipping

AusBS_Vic_Zones["CHG_LBL21"].value_counts(dropna=False)

CHG_LBL21
No change      380
New            114
Name change     30
Name: count, dtype: int64

In [21]:
AusBS_Vic_Zones["GCC_NAME21"].unique()

<ArrowStringArray>
[                          'Rest of Vic.',
                      'Greater Melbourne',
 'Migratory - Offshore - Shipping (Vic.)',
                'No usual address (Vic.)']
Length: 4, dtype: str